# Generated by Django 3.2.5 on 2022-06-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('Category', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=10, null=True)),
                ('Production_country', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('recomended_devices', models.ManyToManyField(related_name='aa', to='home.Products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='home.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('category_products', models.ManyToManyField(related_name='categories', to='home.Products')),
            ],
        ),
    ]
